#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/5/17 11:23
# @Author  : jiakang
# @File    : motor
# @Software: IntelliJ IDEA
# sman_notes: custom script 'motor'

import sys

# print('motor %s' % sys.argv)
# print('')
print('hi, this is custom script \'motor\', you input: %s' % sys.argv[1:])
print (1)
print (2)
print (3)
print (4)
